import type { Metadata } from "next";
import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const NanumSquare = localFont({
  src: "../public/fonts/NanumSquareR.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={NanumSquare.className}>{children}</body>
    </html>
  );
}
